apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "django-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
